### ISSUE TITLE
aaaaaaaaaaaaaaaaaa - aaaaaaaaaaaa

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#105]
```yaml
{
    "date": "2021-01-10",
    "title": "aaaaaaaaaaaa",
    "author": "aaaaaaaaaaaaaaaaaa",
    "credit": "",
    "video_url": "https://player.vimeo.com/video/336812660",
    "description": "aaaaaaaaaaaaaaaaaaaaaa",
    "source": "",
    "fields": [
        "aa"
    ],
    "subfields": [
        "a"
    ],
    "tags": [
        "a"
    ]
}
```
[object Object]
