### ISSUE TITLE
aaaaaaaaaaaaaa - aaaaaaaaaaa

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#107]
```yaml
{
    "date": "2021-01-10",
    "title": "aaaaaaaaaaa",
    "author": "aaaaaaaaaaaaaa",
    "credit": "",
    "video_url": "https://player.vimeo.com/video/336812660",
    "description": "aaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "source": "",
    "fields": [
        "a"
    ],
    "subfields": [
        "a"
    ],
    "tags": [
        "a"
    ]
}
```
