### ISSUE TITLE
byyytes - NEVER FORGET how to INTEGRATE BY PARTS! A visual explanation of IBP

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#180]
```yaml
{
    "date": "2021-01-13",
    "title": "A Visual Representation of Integration By Parts",
    "author": "byyytes",
    "credit": "https://www.youtube.com/channel/UCTLYbIZxyKFBT93YtIgvtEg",
    "video_url": "https://www.youtube.com/embed/73E1rrZ2SqI",
    "description": "A visual explanation of Integration By Parts. I chose to make a video on IBP because it's the thing from calculus class I never understood that shows up most often. I sat down with the formula for a bit, and cranked out a nice visual explanation. The video took much longer.",
    "source": "",
    "fields": [
        "Mathematics"
    ],
    "subfields": [
        "Calculus"
    ],
    "tags": [
        "Integration",
        "Integration By Parts"
    ]
}
```
[![Video - Click to watch](https://img.youtube.com/vi/73E1rrZ2SqI/0.jpg)](https://www.youtube.com/watch?v=73E1rrZ2SqI "Video - Click to watch")
Note: Editing the video_url will not update this thumbnail.
