### ISSUE TITLE
byyytess - A Visual Representation of Integration By Parts

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#182]
```yaml
{
    "date": "2021-02-10",
    "state": "submitted",
    "title": "A Visual Representation of Integration By Parts",
    "author": "byyytess",
    "github_user": "",
    "credit": "https://www.youtube.com/channel/UCTLYbIZxyKFBT93YtIgvtEg",
    "video_url": "https://www.youtube.com/embed/73E1rrZ2SqI",
    "description": "descriptionaaaaaaaaaaaaaaaaaa",
    "source": "",
    "fields": [
        "Mathematics"
    ],
    "subfields": [
        "Calculus"
    ],
    "tags": [
        "Integration",
        "Integration BP"
    ],
    "language": "en",
    "version": "0.1.1"
}
```
[![Video - Click to watch](https://img.youtube.com/vi/73E1rrZ2SqI/0.jpg)](https://www.youtube.com/watch?v=73E1rrZ2SqI "Video - Click to watch")
Note: Editing the video_url will not update this thumbnail.
