### ISSUE TITLE
aa - aaaaaaaaaa

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#185]
```yaml
{
    "date": "2021-02-10",
    "state": "submitted",
    "title": "aaaaaaaaaa",
    "author": "aa",
    "github_user": "",
    "credit": "",
    "video_url": "https://www.youtube.com/embed/73E1rrZ2SqI",
    "description": "aaaaaaaaaaaaaaaaaaaaaaa",
    "source": "",
    "fields": [
        "a"
    ],
    "subfields": [
        "a"
    ],
    "tags": [
        "a"
    ],
    "language": "en",
    "version": "0.3.0"
}
```
[![Video - Click to watch; the missing thumbnail likely means the video_url is incorrect.](https://img.youtube.com/vi/73E1rrZ2SqI/0.jpg)](https://www.youtube.com/watch?v=73E1rrZ2SqI "Video - Click to watch")
Note: Editing the video_url will not update this thumbnail.
