### ISSUE TITLE
aa - aaaaaa

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#186]
```yaml
{
    "date": "2021-02-13",
    "state": "submitted",
    "title": "aaaaaa",
    "author": "aa",
    "github_user": "",
    "credit": "",
    "video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "description": "aaaaaaaaaaaaaaaaaaaa",
    "source": "",
    "fields": [
        "a"
    ],
    "subfields": [
        "a"
    ],
    "tags": [
        "a"
    ],
    "language": "en",
    "version": "0.2.0"
}
```
[![Video - Click to watch; the missing thumbnail likely means the video_url is incorrect.](https://img.youtube.com/vi/dQw4w9WgXcQ/0.jpg)](https://www.youtube.com/watch?v=dQw4w9WgXcQ "Video - Click to watch")
Note: Editing the video_url will not update this thumbnail.
