### ISSUE TITLE
aaaaaa - aaaaaaaaaaaaaaa

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#187]
```yaml
{
    "date": "2021-02-14",
    "state": "unreviewed",
    "title": "aaaaaaaaaaaaaaa",
    "author": "aaaaaa",
    "github_user": "",
    "credit": "",
    "video_url": "https://player.vimeo.com/video/148751763",
    "description": "aaaaaaaaaaaaaaaaaaaaaaa",
    "source": "",
    "fields": [
        "a"
    ],
    "subfields": [
        "a"
    ],
    "tags": [
        "a"
    ],
    "language": "en",
    "version": "0.2.0"
}
```
[![Video - Click to watch; the missing thumbnail likely means the video_url is incorrect.](https://i.vimeocdn.com/video/547780029_295x166.jpg)](https://vimeo.com/148751763 "Video - Click to watch")
Note: Editing the video_url will not update this thumbnail.
