### ISSUE TITLE
aaaaaaaaa - aaaaaaaaaaa

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#188]
```yaml
{
    "date": "2021-02-14",
    "title": "aaaaaaaaaaa",
    "author": "aaaaaaaaa",
    "github_user": "",
    "credit": "",
    "video_url": "https://player.vimeo.com/video/148751763",
    "description": "aaaaaaaaaaaaaaaaaaaaaa",
    "source": "",
    "fields": [
        "a"
    ],
    "subfields": [
        "a"
    ],
    "tags": [
        "a"
    ],
    "language": "en",
    "version": "0.2.0"
}
```
[![Video - Click to watch; a missing thumbnail likely means the video_url is incorrect.](https://i.vimeocdn.com/video/547780029_295x166.jpg)](https://vimeo.com/148751763 "Video - Click to watch")
Note: If video_url has been updated, this thumbnail will not update.
