### ISSUE TITLE
aaaaaaaaaaaaaaaaaaaaaa - 1234

### ISSUE THREAD

**Issue by JBAB2703** [WampyCakes/temp-manim-projects#193]
```yaml
{
    "date": "2021-02-16",
    "state": "unreviewed",
    "title": "11111",
    "author": "aaaaaaaaaaaaaaaaaaaaaa",
    "credit": true,
    "video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "description": "aaaaaaaaaaaaaaaaaaaaaaa",
    "source": "",
    "fields": [
        "aaaa"
    ],
    "subfields": [
        "aaaa"
    ],
    "tags": [
        "aaaa"
    ],
    "language": "en",
    "version": "3b1b"
}
```
[![Video - Click to watch; a missing thumbnail likely means the video_url is incorrect.](https://img.youtube.com/vi/dQw4w9WgXcQ/0.jpg)](https://www.youtube.com/watch?v=dQw4w9WgXcQ "Video - Click to watch")
Note: If `video_url` has been updated, this thumbnail will not update.
