### ISSUE TITLE
aa - adsasdasd

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#250]
```yaml
{
    "date": "2021-06-08",
    "state": "unreviewed",
    "title": "adsasdasd",
    "author": "aa",
    "credit": true,
    "video_url": "https://www.youtube.com/embed/QJYmyhnaaek",
    "description": "aaaaaaaaaaaaaaaaaaaaaaaaaa",
    "source": "",
    "fields": [
        "a"
    ],
    "subfields": [
        "a"
    ],
    "tags": [
        "a"
    ],
    "language": "en",
    "version": "0.3.0"
}
```
[![Video - Click to watch; a missing thumbnail likely means the video_url is incorrect.](https://img.youtube.com/vi/QJYmyhnaaek/0.jpg)](https://www.youtube.com/watch?v=QJYmyhnaaek "Video - Click to watch")
Note: If `video_url` has been updated, this thumbnail will not update.
