### ISSUE TITLE
aa - 

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#251]
```yaml
{
    "date": "2021-06-15",
    "state": "unreviewed",
    "title": "",
    "author": "aa",
    "credit": false,
    "video_url": "https://player.vimeo.com/video/undefined",
    "description": "",
    "source": "",
    "fields": [
        ""
    ],
    "subfields": [
        ""
    ],
    "tags": [
        ""
    ],
    "language": "en",
    "version": ""
}
```
Thumbnail not available.
