### ISSUE TITLE
aa - sfddsf

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#257]
```yaml
{
    "date": "2021-06-15",
    "state": "unreviewed",
    "title": "sfddsf",
    "author": "aa",
    "credit": true,
    "video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "description": "aaaaaaaaaaaaaaaaaaaaaaaa",
    "source": "",
    "fields": [
        "a"
    ],
    "subfields": [
        "a"
    ],
    "tags": [
        "a"
    ],
    "language": "en",
    "version": "3b1b"
}
```
[![Video - Click to watch; a missing thumbnail likely means the video_url is incorrect.](https://img.youtube.com/vi/dQw4w9WgXcQ/0.jpg)](https://www.youtube.com/watch?v=dQw4w9WgXcQ "Video - Click to watch")
Note: If `video_url` has been updated, this thumbnail will not update.
