### ISSUE TITLE
aa - sdfdfdd

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#265]
```yaml
{
    "date": "2021-06-15",
    "state": "unreviewed2",
    "title": "sdfdfdd",
    "author": "aa",
    "credit": true,
    "video_url": "https://player.vimeo.com/video/148751763",
    "description": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "source": "",
    "fields": [
        "a"
    ],
    "subfields": [
        "a"
    ],
    "tags": [
        "a"
    ],
    "language": "en",
    "version": "3b1b"
}
```
[![Video - Click to watch; a missing thumbnail likely means the video_url is incorrect.](https://i.vimeocdn.com/video/547780029_295x166)](https://vimeo.com/148751763 "Video - Click to watch")
Note: If `video_url` has been updated, this thumbnail will not update.
