### ISSUE TITLE
Grant Sanderson - All possible pythagorean triples, visualized

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#69]
```yaml
{
    "date": "2020-12-31",
    "title": "All possible pythagorean triples, visualized",
    "author": "Grant Sanderson",
    "credit": "https://github.com/3b1b",
    "video_url": "https://player.vimeo.com/video/336812660",
    "description": "The pythagorean triples like (3, 4, 5), (5, 12, 13), etc. all follow a nice pattern which complex numbers expose in a beautiful way.",
    "source": "https://github.com/3b1b/manim",
    "fields": "Mathematics",
    "subfields": "Complex Numbers",
    "tags": "Pythagorean Theorem, Pythagorean Triples"
}
```
<center>[![Video - Click to watch](https://i.vimeocdn.com/video/784397921_295x166.jpg)](https://vimeo.com/video/336812660 "Video - Click to watch")</center>
