### ISSUE TITLE
Grant Sanderson - All possible pythagorean triples, visualized

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#73]
```yaml
{
    "date": "2021-01-06",
    "title": "An entirely edited entry!",
    "author": "Grant Sanderson",
    "credit": "https://github.com/3b1b",
    "video_url": "https://www.youtube.com/watch?v=QJYmyhnaaek",
    "description": "The pythagorean triples like (3, 4, 5), (5, 12, 13), etc. all follow a nice pattern which complex numbers expose in a beautiful way.",
    "source": "https://github.com/3b1b/manim",
    "fields": "Mathematics",
    "subfields": "Complex Numbers",
    "tags": "Pythagorean Theorem, Pythagorean Triples"
}
```
[![Video - Click to watch](https://img.youtube.com/vi/QJYmyhnaaek/0.jpg)](https://www.youtube.com/watch?v=QJYmyhnaaek "Video - Click to watch")
