### ISSUE TITLE
aaaaaa - aaaaaaaaaaa

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#82]
```yaml
{
    "date": "2021-01-08",
    "title": "aaaaaaaaaaa",
    "author": "aaaaaa",
    "credit": "",
    "video_url": "https://www.youtube.com/embed/QJYmyhnaaek",
    "description": "aaaaaaaaaaaaaaaaaaaaaaaaa",
    "source": "",
    "fields": [
        "a"
    ],
    "subfields": [
        "a"
    ],
    "tags": [
        "a"
    ]
}
```
[![Video - Click to watch](https://img.youtube.com/vi/QJYmyhnaaek/0.jpg)](https://www.youtube.com/watch?v=QJYmyhnaaek "Video - Click to watch")
Note: Editing the video_url will not update this thumbnail.
