### ISSUE TITLE
aaaaaaaa - aaaaaaaa

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#85]
```yaml
{
    "author": "aaaaaaaa",
    "credit": "",
    "date": "2021-01-09",
    "description": "aaaaaaaaaaaaaaaaaaaa",
    "fields": [
        "a"
    ],
    "source": "",
    "subfields": [
        "a"
    ],
    "tags": [
        "a"
    ],
    "title": "aaaaaaaa",
    "video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ"
}
```
[![Video - Click to watch](https://img.youtube.com/vi/dQw4w9WgXcQ/0.jpg)](https://www.youtube.com/watch?v=dQw4w9WgXcQ "Video - Click to watch")
Note: Editing the video_url will not update this thumbnail.
