### ISSUE TITLE
aaaaaaaaa - aaaaaaaaaa

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#88]
```yaml
{
    "author": "aaaaaaaaa",
    "credit": "",
    "date": "2021-01-09",
    "description": "aaaaaaaaaaaaaaaaaaaa",
    "fields": [
        "a"
    ],
    "source": "",
    "subfields": [
        "a"
    ],
    "tags": [
        "a"
    ],
    "title": "aaaaaaaaaa",
    "video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ"
}
```
