### ISSUE TITLE
undefined - undefined

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#91]
```yaml
{
    "cf": {
        "tlsExportedAuthenticator": {
            "clientFinished": "665f15199fe01f4d983039ed1bce7c500f4ea9c7e5b865849e0a4b02470ba4d9",
            "clientHandshake": "6471fcfff42ac3a336da99aa93bb92e7ba88ebf385497c8cd85ae4ee4f73486a",
            "serverHandshake": "5acb028a38614fbfe603d6fd7fb7ddefc899de46aaaf8f84e028d2b5ce0139fa",
            "serverFinished": "4e504cf7e005cc905f54432259fff2db77a8f377337c115a6aaeaa8750344155"
        },
        "tlsVersion": "TLSv1.3",
        "httpProtocol": "HTTP/2",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "edgeRequestKeepAliveStatus": 1,
        "requestPriority": "weight=42;exclusive=0;group=13;group-weight=241",
        "country": "US",
        "clientAcceptEncoding": "gzip, deflate, br",
        "clientTcpRtt": 77,
        "colo": "ATL",
        "tlsClientAuth": {
            "certIssuerDNLegacy": "",
            "certIssuerDN": "",
            "certIssuerDNRFC2253": "",
            "certSubjectDNLegacy": "",
            "certNotAfter": "",
            "certVerified": "NONE",
            "certFingerprintSHA1": "",
            "certSubjectDN": "",
            "certFingerprintSHA256": "",
            "certNotBefore": "",
            "certSerial": "",
            "certPresented": "0",
            "certSubjectDNRFC2253": ""
        },
        "asn": 6181
    },
    "fetcher": {},
    "redirect": "manual",
    "headers": {},
    "url": "https://showcase.manim.workers.dev/",
    "method": "POST",
    "bodyUsed": false,
    "body": {
        "locked": false
    }
}
```
