### ISSUE TITLE
aaaaaaa - aaaaaaaaaaaaaaaa

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#93]
```yaml
{
    "date": "2021-01-09",
    "title": "aaaaaaaaaaaaaaaa",
    "author": "aaaaaaa",
    "credit": "",
    "video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "description": "aaaaaaaaaaaaaaaaaaaa",
    "source": "",
    "fields": [
        "a"
    ],
    "subfields": [
        "a"
    ],
    "tags": [
        "a"
    ]
}
```
