### ISSUE TITLE
aaaaaaaaaaa - aaaaaaaaaaaa

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#96]
```yaml
{
    "date": "2021-01-09",
    "title": "aaaaaaaaaaaa",
    "author": "aaaaaaaaaaa",
    "credit": "",
    "video_url": "https://player.vimeo.com/video/336812660",
    "description": "aaaaaaaaaaaaaaaaaaaaaaaa",
    "source": "",
    "fields": [
        "a"
    ],
    "subfields": [
        "a"
    ],
    "tags": [
        "a"
    ]
}
```
[![Video - Click to watch](https://i.vimeocdn.com/video/784397921_295x166.jpg)](https://vimeo.com/video/336812660 "Video - Click to watch")
Note: Editing the video_url will not update this thumbnail.
