### ISSUE TITLE
aaaaaaaaaaaaa - aaaaaaaaaaaaaaaaaa

### ISSUE THREAD

**Issue by WampyCakes** [WampyCakes/temp-manim-projects#98]
```yaml
{
    "date": "2021-01-09",
    "title": "aaaaaaaaaaaaaaaaaa",
    "author": "aaaaaaaaaaaaa",
    "credit": "",
    "video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "description": "aaaaaaaaaaaaaaaaaaaaaaaaaa",
    "source": "",
    "fields": [
        "a"
    ],
    "subfields": [
        "a"
    ],
    "tags": [
        "a"
    ]
}
```
[![Video - Click to watch](https://img.youtube.com/vi/dQw4w9WgXcQ/0.jpg)](https://www.youtube.com/watch?v=dQw4w9WgXcQ "Video - Click to watch")
Note: Editing the video_url will not update this thumbnail.
